version: '3.8'

services:
  web:
    build: .
    container_name: fun-web-1
    ports:
      - "8088:1407"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/app
      - static_files:/app/staticfiles
      - db_data:/app/db
    command: gunicorn --bind 0.0.0.0:1407 root.wsgi:application --workers 3
    networks:
      - web

volumes:
  db_data:
  static_files:

networks:
  web:
    external: true
